project:
  type: website

website:
  title: "ISSS608-VAA"
  navbar:
    left:
      - text: "Hands-on Exercise"
        menu:
          - text: "Hands-on Exercise 1"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
          - text: "Hands-on Exercise 2"
            href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
          - text: "Hands-on Exercise 3_1"
            href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03(1).html"  
          - text: "Hands-on Exercise 3_2"
            href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03(2).html" 
          - text: "Hands-on Exercise 4_1"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04(1).html"
          - text: "Hands-on Exercise 4_2"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04(2).html"
          - text: "Hands-on Exercise 4_3"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04(3).html"
          - text: "Hands-on Exercise 4_4"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04(4).html"
          - text: "Hands-on Exercise 5"
            href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05.html"
      - text: "Take-home Exercise"
        menu:
          - text: "Take-home Exercise 1_1"
            href: "Take-home_Ex/Take-home_Ex01/Take-home_Ex01(1).html"
          - text: "Take-home Exercise 1_2"
            href: "Take-home_Ex/Take-home_Ex01/Take-home_Ex01(2).html"
      - text: "In-class Exercise"
        menu:
          - text: "In-class Exercise 3"
            href: "In-class_Ex/In-class_Ex03.html"
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: morph
    css: styles.css
    toc: true

editor: visual

